version: '3.8'

services:
  bot:
    build: .
    command: python -m main  
    env_file:
      - ./.env
    environment:
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT}
      LOG_FILE_PATH_BOT: ${LOG_FILE_PATH_BOT}
      LOG_FILE_PATH_DB: ${LOG_FILE_PATH_DB}
    restart: always
    depends_on:
      - postgres
      - mongo
  postgres:
    image: postgres:latest
    restart: on-failure
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}  
      POSTGRES_HOST: ${POSTGRES_HOST}  

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    restart: on-failure
    env_file:
      - ./.env
    environment:
      MONGO_URL: ${MONGO_URL}
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  pgdata:
  mongodata:
